### PR TITLE
replaces use of deprecated transferPropsTo with object-assign shim

### PR DESCRIPTION
**Pull request by tacomanator**
Method transferPropsTo deprecated 0.12 and removed in 0.13.

### CODE REVIEW

**Comment by seanadkinson** [comment]
Thanks, will push an update

**Comment by seanadkinson** [comment]
v1.0.1 is up

**Comment by tacomanator** [comment]
Thanks for merging so quickly :)

**Comment by seanadkinson** [comment]
Np, thanks for the PR

**Pull request merged**
